### ISSUE TITLE
Main icon is not showing

### ISSUE THREAD

**Issue by oturan233** [Tom-Hirschberger/MMM-OpenWeatherForecast#11]
Hi,

Thanks for this great weather module.

I tried many configurations and almost all iconsets, however My main icon (current weather big icon) not showing. I can see the icons on daily view, or hourly view but no icons on main view.  Do you have any idea?

<img width="170" alt="VNC-Viewer-6 20 113-Windows-64bit111_H1L1pqrVKS" src="https://github.com/user-attachments/assets/ced6ec60-8d35-41fa-8988-28e55aa265bc" />

My config is below:

 {
    module: "MMM-OpenWeatherForecast",
    position: "top_right",
    config: {
      apikey: "XXXXXXXXXXXXXXXXXXXXX", //only string here
      latitude: "XXXXXXX",            //number works here
      longitude: "XXXXXXX",          //so does a string
iconset: "4c",
      colored: true,
showCurrentConditions: true,
extraCurrentConditions: {
        highLowTemp: true,
        precipitation: true,
        sunrise: true,
        sunset: true,
        wind: true,
        barometricPressure: false,
        humidity: true,
        dewPoint: false,
        uvIndex: false,
        visibility: false
      },
displayKmhForWind: true,
showHourlyForecast: false,
forecastLayout: "table",
dailyForecastTableHeaderText: "Throughout the week",
      showDailyForecast: true,
      showDailyTableHeaderRow: true,
      maxDailiesToShow: 5,
      dailyExtras: {
        precipitation: true,
        sunrise: false,
        sunset: false,
        wind: true,
        barometricPressure: false,
        humidity: false,
        dewPoint: false,
        uvIndex: false
      },
label_days: [
          'Paz',
          'Pzts',
          'Sal',
          'Cars',
          'Pers',
          'Cuma',
          'Cmts'
        ]
        }
    },

**Comment by oturan233** [comment]
Please ignore my question. After couple of minutes, icon appeared. May be there is a delay for this main icon, I don't understand. But now it's ok. Thanks in anyway.

**Comment by Tom-Hirschberger** [comment]
Hi, and thanks. The main tribute goes to the former developers. I only forked the original module to make it work with the new api version. 

Great to hear it works. The icons are loaded directly of your mirror. I do not know why it is delayed.
