### ISSUE TITLE
"Loading" - But no data is shown

### ISSUE THREAD

**Issue by Rene1695** [Tom-Hirschberger/MMM-OpenWeatherForecast#7]
Hi,

I tried to add your model and everything you mentioned in the wiki (aka: different baseURL for API 3.0 or 2.5). I also deleted all of the API Keys in OpenWeather and created a new one.

Sadly, Everything I Can see is the word "loading" but no data is shown... There is also nothing in the log files. Do you have any ideas what I am getting wrong? Do I need a payed subscription in open weather? I thought the free one should be enough right? 

I am running MagicMirror in Docker on an Unraid server. 

![image](https://github.com/user-attachments/assets/a9673259-665a-488f-b2fd-f073569a8064)

![image](https://github.com/user-attachments/assets/531c725a-6770-4a28-a9c8-9be20b530ca0)

**Comment by Tom-Hirschberger** [comment]
Hi,

just wanted to write a answer as I now have access zo my mobile.

Yes you need to subscribe to the 3.0 Api which requires paymanet information. But as long as you call the api less than i think 4000 times a day it is free.

25.09.2024 15:51:22 René ***@***.***>:

**Comment by calonmerc** [comment]
Just a note on this: the limit is 1000 calls per day, I keep hitting this limit with this module, so I've manually decreased the call frequency.

**Comment by Rene1695** [comment]
@calonmerc So you set the updateInterval to a higher value? What have you set it to? First thing I did in OpenWeather was to set the limit to 1000 calls, so I hopefully never have to pay anything ..

**Comment by Tom-Hirschberger** [comment]
The default interval of the module is 10 minutes which results in 144 calls a day. 
Only you change the interval to a lower value you should hit the limit.

But be careful if you use the key in more than this module or i.e. access your mirror with more than one browser (i.e. the builtin electron and additionally by pc) the number of calls multiplies by the number of instances.

**Comment by Rene1695** [comment]
Thanks for that info, didn't know that! I will let it set to 10 minutes and I think that is fine. Since we are talking here, I have two additional small questions: 

I set the language to "de" but I saw that Alert messages are in englisch. Although they are from "Deutscher Wetterdienst" they are transported in englisch.. Do you know if this can be set to German? Since this is a German weather station I was wondering why it is in English.. 

In the current weather condition window there is this percentage value if it will rain or not. In my case the unit seems to be wrong. Did I mess something up in the CSS or is this might be a bug? In the forecast window the unit is correct.
![image](https://github.com/user-attachments/assets/23a23598-c24d-4477-b0af-4e882fb6e9c0)


Thanks again and have a nice evening :)

**Comment by Tom-Hirschberger** [comment]
The module itself does not do any translation but uses the data as it is provided by the api.

I use the module in German setting, too but I have hidden the alerts section with css (display: none) and use MMM-DWD-WarnWeather for the warnings.

The unit `mm` is correct. The value is the expected amount of rain and not the possibility that it will rain.

**Comment by Rene1695** [comment]
Thank you so much :)

**Comment by calonmerc** [comment]
> @calonmerc So you set the `updateInterval` to a higher value? What have you set it to? First thing I did in OpenWeather was to set the limit to 1000 calls, so I hopefully never have to pay anything ..

Interestingly,  I finally got a usage link from them and I received an automatic api key block with less than 400 calls per day (I do have two displays). I already have my account set to max 1000 calls per day. Seems like they might have a bug in their system?
