### ISSUE TITLE
Bottom margin at the end of the module 

### ISSUE THREAD

**Issue by Rene1695** [Tom-Hirschberger/MMM-OpenWeatherForecast#8]
Hi,

sorry just another short question. I am looking inside your CSS file for the definition of the margin that is used at the very end of the module (right after the line where it says "powered by OpenWeather").

I was thinking that it is in this region but I tried some stuff and I didn't found it so far. 

```
.MMM-OpenWeatherForecast .forecast-container.hourly + .forecast-container.daily {
  border-top: none;
}

/* Tiled Layout */

.MMM-OpenWeatherForecast .wrapper.tiled .forecast-container {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: flex-start;
  align-content: flex-start;
  align-items: flex-start;
  margin-bottom: 0 30px;
  border-top: solid 1px #222;
}

.MMM-OpenWeatherForecast .wrapper.with-forecast-header.tiled .forecast-container {
  border-top: none;
}

.MMM-OpenWeatherForecast .wrapper.tiled .forecast-container .forecast-item {
  flex-grow: 1;
  flex-shrink: 1;
  min-width: 100px;
  padding: 10px 5px 10px 5px;
  border-bottom: solid 1px #222;
}
```

![image](https://github.com/user-attachments/assets/a2cc5a5c-357f-4f21-b936-e978a4f3f398)

Thanks for helping :)

**Comment by Tom-Hirschberger** [comment]
No Problem.

As I only forked the module and changed some small parts to get it running with the new api version I do not have a deeper knowledge of the CSS yet.

I will try to take a look and find the correct class.

25.09.2024 17:03:40 René ***@***.***>:

**Comment by Tom-Hirschberger** [comment]
I think the class you are searching for is:

```
.MMM-OpenWeatherForecast .attribution {
  
}
```

**Comment by Tom-Hirschberger** [comment]
You can use the developer view of the browser or Electron (the hotkey in Electron is Strg+Shit+i) to insepct the elements and their classes

**Comment by Rene1695** [comment]
Many thanks :** I didn't know that feature in the browser, wow, this is super easy :)
